// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://muilijjxilogkwazfxlp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11aWxpamp4aWxvZ2t3YXpmeGxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNDQ0MjEsImV4cCI6MjA2OTcyMDQyMX0.uVAxiBkxcnG1JmVVSuI-QkOqLMdvFMpL4rVHAtBHNP4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});